config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  get 'chat_room', to: 'homes#chat_room'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :students

end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
    return unless user

    if user.super_admin?
      can :manage, :all
    else
      can :manage, AdminUser, id: user.id
      can :read, :all
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_enumeration_for :role_id, with: Role, create_helpers: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

  require 'csv'

  enum gender: %i[male female]

  # Full Name of Student
  #
  # @return [String]
  def name
    "#{first_name} #{last_name}"
  end

  # Generates CSV files for Students.
  #
  # @return [void]
  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << column_names
      all.each do |name|
        csv << name.attributes.values_at(*column_names)
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def access_denied(exception)
    redirect_to admin_dashboard_path, alert: exception.message
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/students_controller.rb
# rubocop:disable Style/FrozenStringLiteralComment
# rubocop:enable Style/FrozenStringLiteralComment
# Handles CRUD Operations of Students using ActiveInteraction.
class StudentsController < ApplicationController
  # Renders list of students.
  #
  # @accepts HTML
  # @verb GET
  def index
    @students = ListStudents.run!
    respond_to do |format|
      format.html {}
      format.csv do
        send_data CsvExportWorker.perform_async('student')
      end
    end
  end

  # Build and renders form for new <tt>Student</tt>.
  #
  # @accepts HTML
  # @verb GET
  def new
    @student = CreateStudent.new
  end

  # Creates new <tt>Student</tt> using params.
  #
  # @post_params :student [Hash]
  #   * first_name [String]
  #   * last_name [String]
  #   * course_name [String]
  #   * age [String]
  #
  # @accepts HTML
  # @verb POST
  def create
    @student = CreateStudent.run(student_params)

    if @student.valid?
      flash[:success] = t('controllers.students.flash.success.create_success')
      redirect_to(@student.result)
    else
      render :new
    end
  end

  # Renders for to edit <tt>Student</tt>
  #
  # @get_params :id [String] Student#id
  #
  # @accepts HTML
  # @verb GET
  def edit
    @student = Student.find(params[:id])
  end

  # Renders <tt>Student</tt> details.
  #
  # @get_params :id [String] Student#id
  #
  # @accepts HTML
  # @verb GET
  def show
    @student = find_student!
  end

  # Updates <tt>Student</tt> details.
  #
  # @get_params :id [String] Student#id
  # @post_params :student [Hash]
  #   * first_name [String]
  #   * last_name [String]
  #   * course_name [String]
  #   * age [String]
  #
  # @accepts HTML
  # @verb PATCH
  def update
    inputs = { student: find_student! }.reverse_merge(student_params)
    @student = UpdateStudent.run(inputs)

    if @student.valid?
      flash[:success] = t('controllers.students.flash.success.update_success')
      redirect_to(@student.result)
    else
      render(:edit)
    end
  end

  private

  # Finds <tt>Student</tt>
  #
  # @return [Student]
  def find_student!
    outcome = FindStudent.run(params)
    outcome.result
  end

  # Whitelists permitted params (attributes) of Students.
  #
  # @return [Object<ActionController::Parameters>]
  def student_params
    params.require(:student).permit(:first_name, :last_name, :course_name, :age, :gender)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/homes/chat_room.html.haml
#main
  %h2= t('views.home.chat_room')
  #chat_body
    #messages
    %form#send_message
      %input#message{ name: 'message', type: 'text' }/
      %button= t('views.home.send')
  #modal
    %div
      %h4= t('views.home.add_name')
      %form#set_name
        %input#add_name{ name: 'add_name', type: 'text' }/
        %button= t('general.submit')

app/views/homes/index.html.haml
%h1{ align: 'center' }
  =t('general.welcome')
- if user_signed_in?
  %h4{ align: 'center' }
    Logged in as
    = succeed "." do
      %strong= current_user.email
    %p
      = link_to t('views.users.edit_profile'), edit_user_registration_path
= link_to t('views.home.enter_chat_room'), chat_room_path

app/views/layouts/_messages.html.haml
.row
  .col-xs-10.col-xs-offset-1
    - flash.each do |name, msg|
      %div{ class: "alert alert-#{"#{name}"}"}
        %a.close{"data-dismiss" => "alert", href: "#"} ×
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'httpequiv' => 'Content-Type' }/
    %title= t('general.account_management')
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    %p.navbar-text.float-right
      .navbar-link
        - if user_signed_in?
          = link_to t('general.logout'), destroy_user_session_path, method: :delete
          |
          = link_to t('navigations.students'), students_path
        - else
          = link_to t('general.signup'), new_user_registration_path
          |
          \#{link_to t('general.login'), new_user_session_path}
    = render 'layouts/messages'
    = yield

app/views/students/_form.html.haml
= form_for student, as: :student, url: student.new_record? ? students_path : student_path(student) do |f|
  = render 'users/shared/error_messages', resource: student
  .field
    = f.label t('views.students.first_name')
    = f.text_field :first_name
  %br/
  .field
    = f.label t('views.students.last_name')
    = f.text_field :last_name
  %br/
  .field
    = f.label t('views.students.course_name')
    = f.text_field :course_name
  %br/
  .field
    = f.label t('views.students.age')
    = f.text_field :age
  %br/
  .field
    = f.label t('views.students.gender')
    = f.select :gender,
      options_for_select(Student.genders.map { |key, value| [key.titleize, value] }, student.gender)
  %br/
  = f.submit

app/views/students/edit.html.haml
%h1{ align: 'center' }= t('views.students.edit_student_details')
= render 'form', student: @student

app/views/students/index.html.haml
%h1{ align: 'center' }= t('navigations.students')
%p
  - @students.each do |student|
    %ul
      = student.name
      = link_to t('general.view'), student_path(student)
      |
      = link_to t('general.edit'), edit_student_path(student)
= link_to t('views.students.add_student'), new_student_path
|
= link_to t('general.back'), root_path
|
= link_to t('views.students.download'), students_path(format: 'csv')

app/views/students/new.html.haml
%h1{ align: 'center' }= t('views.students.add_student')
= render 'form', student: @student

app/views/students/show.html.haml
%h1{ align: 'center' }= t('views.students.student_details')
%ul
  = t('views.students.full_name')
  = ": #{@student.name}"
%ul
  = t('views.students.course_name')
  = ": #{@student.course_name}"
%ul
  = t('views.students.age')
  = ": #{@student.age}"
%ul
  = t('views.students.gender')
  = ": #{@student.gender}"
= link_to t('general.back'), students_path

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/